Repository Classy-Potatoes/Server_Classy-Groupware, pull requests merged in 2023-11, with the labels that each got.

#24 Feat/#19/로그인관련
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/common/paging/Pagenation.java
  src/main/java/com/potatoes/cg/common/paging/PagingButtonInfo.java
  src/main/java/com/potatoes/cg/common/paging/PagingResponse.java
  src/main/java/com/potatoes/cg/login/filter/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/potatoes/cg/member/domain/Dept.java
  src/main/java/com/potatoes/cg/member/domain/Job.java
  src/main/java/com/potatoes/cg/member/domain/Member.java
  src/main/java/com/potatoes/cg/member/domain/MemberInfo.java
  src/main/java/com/potatoes/cg/member/domain/type/MemberRole.java
  src/main/java/com/potatoes/cg/member/domain/type/MemberStatus.java
Labels: API, BE, Feature

#25 Feat/#11/쪽지 조회
  src/main/java/com/potatoes/cg/common/exception/CustomException.java
  src/main/java/com/potatoes/cg/common/exception/NotFoundException.java
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/note/domain/Note.java
  src/main/java/com/potatoes/cg/note/domain/Sample.java
  src/main/java/com/potatoes/cg/note/domain/repository/NoteRepository.java
  src/main/java/com/potatoes/cg/note/domain/repository/Sample.java
  src/main/java/com/potatoes/cg/note/domain/type/Sample.java
  src/main/java/com/potatoes/cg/note/dto/request/NoteRequest.java
  src/main/java/com/potatoes/cg/note/dto/response/NoteResponse.java
  src/main/java/com/potatoes/cg/note/dto/response/NotesResponse.java
  src/main/java/com/potatoes/cg/note/dto/response/Sample.java
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
  src/main/java/com/potatoes/cg/note/presentation/Sample.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
  src/main/java/com/potatoes/cg/note/service/Sample.java
Labels: API, BE, Feature

#26 Feat/#2/캘린더
  src/main/java/com/potatoes/cg/calendar/common/exception/BadRequestException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/ConflictException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/CustomException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/ExceptionHandlingController.java
  src/main/java/com/potatoes/cg/calendar/common/exception/ExceptionResponse.java
  src/main/java/com/potatoes/cg/calendar/common/exception/NotFoundException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/ServerInternalException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/calendar/domain/Calendar.java
  src/main/java/com/potatoes/cg/calendar/domain/repository/CalendarRepository.java
  src/main/java/com/potatoes/cg/calendar/domain/type/StatusType.java
  src/main/java/com/potatoes/cg/calendar/dto/request/CalendarCreateRequest.java
  src/main/java/com/potatoes/cg/calendar/dto/request/CalendarUpdateRequest.java
  src/main/java/com/potatoes/cg/calendar/dto/response/ScheduleDetailResponse.java
  src/main/java/com/potatoes/cg/calendar/dto/response/ScheduleResponse.java
  src/main/java/com/potatoes/cg/calendar/presentation/CalendarController.java
  src/main/java/com/potatoes/cg/calendar/service/CalendarService.java
  src/main/java/com/potatoes/cg/common/config/SecurityConfig.java
  src/main/java/com/potatoes/cg/projectSchedule/domain/ProjectSchedule.java
  src/main/java/com/potatoes/cg/projectSchedule/domain/repository/ProjectScheduleRepository.java
  src/main/java/com/potatoes/cg/projectSchedule/presentation/ProjectScheduleController.java
  src/main/java/com/potatoes/cg/projectSchedule/service/ProjectScheduleService.java
Labels: BE, Feature

#28 Feature/#16/품의서작성 개발중
  src/main/java/com/potatoes/cg/approval/domain/Approval.java
  src/main/java/com/potatoes/cg/approval/domain/ApprovalLine.java
  src/main/java/com/potatoes/cg/approval/domain/FileEntity.java
  src/main/java/com/potatoes/cg/approval/domain/Letter.java
  src/main/java/com/potatoes/cg/approval/domain/Reference.java
  src/main/java/com/potatoes/cg/approval/domain/Sample.java
  src/main/java/com/potatoes/cg/approval/domain/repository/ApprovalLineRepository.java
  src/main/java/com/potatoes/cg/approval/domain/repository/ApprovalRepository.java
  src/main/java/com/potatoes/cg/approval/domain/repository/FileEntityRepository.java
  src/main/java/com/potatoes/cg/approval/domain/repository/LetterRepository.java
  src/main/java/com/potatoes/cg/approval/domain/repository/ReferenceRepository.java
  src/main/java/com/potatoes/cg/approval/domain/repository/Sample.java
  src/main/java/com/potatoes/cg/approval/domain/type/ApprovalLineResultType.java
  src/main/java/com/potatoes/cg/approval/domain/type/ApprovalLineWaitingStatusType.java
  src/main/java/com/potatoes/cg/approval/domain/type/ApprovalStatusType.java
  src/main/java/com/potatoes/cg/approval/domain/type/DocumentType.java
  src/main/java/com/potatoes/cg/approval/domain/type/Sample.java
  src/main/java/com/potatoes/cg/approval/dto/request/LetterCreateRequest.java
  src/main/java/com/potatoes/cg/approval/dto/response/Sample.java
  src/main/java/com/potatoes/cg/approval/presentation/ApprovalController.java
  src/main/java/com/potatoes/cg/approval/presentation/Sample.java
  src/main/java/com/potatoes/cg/approval/service/ApprovalService.java
  src/main/java/com/potatoes/cg/approval/service/Sample.java
  src/main/java/com/potatoes/cg/common/domain/BaseEntity.java
  src/main/java/com/potatoes/cg/common/exception/ConflictException.java
  src/main/java/com/potatoes/cg/common/exception/ExceptionHandlingController.java
  src/main/java/com/potatoes/cg/common/exception/ServerInternalException.java
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/common/util/FileUploadUtils.java
Labels: API, BE, Feature

#29 Feat/#11/쪽지 전체 조회, 상세 조회
  src/main/java/com/potatoes/cg/note/domain/repository/NoteRepository.java
  src/main/java/com/potatoes/cg/note/domain/type/NoteStatusType.java
  src/main/java/com/potatoes/cg/note/dto/response/NoteResponse.java
  src/main/java/com/potatoes/cg/note/dto/response/NotesResponse.java
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
Labels: BE, Feature

#30 Feat/#7/프로젝트생성,조회
  build.gradle
  src/main/java/com/potatoes/cg/common/exception/MemberException.java
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/jwt/ProjectMember.java
  src/main/java/com/potatoes/cg/project/domain/Project.java
  src/main/java/com/potatoes/cg/project/domain/ProjectParticipant.java
  src/main/java/com/potatoes/cg/project/domain/ProjectParticipantId.java
  src/main/java/com/potatoes/cg/project/domain/Sample.java
  src/main/java/com/potatoes/cg/project/domain/repository/DeptRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectParticipantRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/Sample.java
  src/main/java/com/potatoes/cg/project/domain/repository/memberRepository.java
  src/main/java/com/potatoes/cg/project/domain/type/ProjectStatusType.java
  src/main/java/com/potatoes/cg/project/domain/type/Sample.java
  src/main/java/com/potatoes/cg/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/potatoes/cg/project/dto/response/ProjectResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/ProjectsResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/Sample.java
  src/main/java/com/potatoes/cg/project/presentation/ProjectController.java
  src/main/java/com/potatoes/cg/project/presentation/Sample.java
  src/main/java/com/potatoes/cg/project/service/ProjectService.java
  src/main/java/com/potatoes/cg/project/service/Sample.java
Labels: BE

#31 Feat / #2 / Calendar2
  src/main/java/com/potatoes/cg/calendar/common/exception/BadRequestException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/ConflictException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/CustomException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/ExceptionHandlingController.java
  src/main/java/com/potatoes/cg/calendar/common/exception/ExceptionResponse.java
  src/main/java/com/potatoes/cg/calendar/common/exception/NotFoundException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/ServerInternalException.java
  src/main/java/com/potatoes/cg/calendar/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/calendar/dto/response/ScheduleResponse.java
  src/main/java/com/potatoes/cg/calendar/service/CalendarService.java
  src/main/java/com/potatoes/cg/common/exception/BadRequestException.java
  src/main/java/com/potatoes/cg/common/exception/NotFoundException.java
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
Labels: BE

#32 Feat/#19/로그인관련 사전등록완료
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/login/filter/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/potatoes/cg/member/domain/MemberInfo.java
  src/main/java/com/potatoes/cg/member/domain/repository/DeptRepository.java
  src/main/java/com/potatoes/cg/member/domain/repository/InfoRepository.java
  src/main/java/com/potatoes/cg/member/domain/repository/JobRepository.java
  src/main/java/com/potatoes/cg/member/dto/request/InfoRegistRequest.java
  src/main/java/com/potatoes/cg/member/dto/request/MemberSignupRequest.java
  src/main/java/com/potatoes/cg/member/dto/response/ProfileResponse.java
  src/main/java/com/potatoes/cg/member/presentation/AdminController.java
  src/main/java/com/potatoes/cg/member/presentation/MemberController.java
  src/main/java/com/potatoes/cg/member/service/AdminService.java
  src/main/java/com/potatoes/cg/member/service/MemberService.java
Labels: API, BE, Feature

#33 Fix/#7/프로젝트파일이름수정
  src/main/java/com/potatoes/cg/approval/service/ApprovalService.java
  src/main/java/com/potatoes/cg/calendar/domain/Calendar.java
  src/main/java/com/potatoes/cg/calendar/domain/repository/CalendarRepository.java
  src/main/java/com/potatoes/cg/calendar/domain/type/StatusType.java
  src/main/java/com/potatoes/cg/calendar/dto/request/CalendarCreateRequest.java
  src/main/java/com/potatoes/cg/calendar/dto/request/CalendarUpdateRequest.java
  src/main/java/com/potatoes/cg/calendar/dto/response/ScheduleDetailResponse.java
  src/main/java/com/potatoes/cg/calendar/dto/response/ScheduleResponse.java
  src/main/java/com/potatoes/cg/calendar/presentation/CalendarController.java
  src/main/java/com/potatoes/cg/calendar/service/CalendarService.java
  src/main/java/com/potatoes/cg/common/exception/CustomException.java
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/jwt/CustomUser.java
  src/main/java/com/potatoes/cg/note/dto/response/NoteResponse.java
  src/main/java/com/potatoes/cg/project/domain/Project.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectDeptRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectmemberRepository.java
  src/main/java/com/potatoes/cg/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/potatoes/cg/project/presentation/ProjectController.java
  src/main/java/com/potatoes/cg/project/service/ProjectService.java
  src/main/java/com/potatoes/cg/projectSchedule/domain/ProjectSchedule.java
  src/main/java/com/potatoes/cg/projectSchedule/domain/repository/ProjectScheduleRepository.java
Labels: Bug

#34 Feat/#12/받은 쪽지, 보낸 쪽지 삭제
  src/main/java/com/potatoes/cg/approval/presentation/ApprovalController.java
  src/main/java/com/potatoes/cg/approval/service/ApprovalService.java
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/note/domain/Note.java
  src/main/java/com/potatoes/cg/note/dto/request/NoteCreateRequest.java
  src/main/java/com/potatoes/cg/note/dto/response/NoteResponse.java
  src/main/java/com/potatoes/cg/note/dto/response/NotesResponse.java
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
  src/main/java/com/potatoes/cg/projectSchedule/domain/ProjectSchedule.java
  src/main/java/com/potatoes/cg/projectSchedule/domain/repository/ProjectScheduleRepository.java
  src/main/java/com/potatoes/cg/projectSchedule/presentation/ProjectScheduleController.java
  src/main/java/com/potatoes/cg/projectSchedule/service/ProjectScheduleService.java
Labels: API, BE, Feature

#41 Feat/#37/보낸 쪽지함 검색(member 엔티티 변경으로 인한 memberInfo -> memberInfoSelect 변경)
  src/main/java/com/potatoes/cg/note/domain/repository/NoteRepository.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
Labels: API, BE, Feature
