Repository Classy-Potatoes/Server_Classy-Groupware, pull requests merged in 2023-12, with the labels that each got.

#47 Feature/#8,#46/프로젝트일반글작성,조회,삭제,프로젝트참여자초대하기
  src/main/java/com/potatoes/cg/approval/domain/type/ApprovalFileType.java
  src/main/java/com/potatoes/cg/common/exception/type/ExceptionCode.java
  src/main/java/com/potatoes/cg/jwt/CustomUser.java
  src/main/java/com/potatoes/cg/member/domain/repository/MemberRepository.java
  src/main/java/com/potatoes/cg/project/domain/PostFile.java
  src/main/java/com/potatoes/cg/project/domain/Project.java
  src/main/java/com/potatoes/cg/project/domain/ProjectParticipant.java
  src/main/java/com/potatoes/cg/project/domain/ProjectParticipantId.java
  src/main/java/com/potatoes/cg/project/domain/ProjectPost.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectMemberRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectParticipantRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectPostRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectmemberRepository.java
  src/main/java/com/potatoes/cg/project/domain/type/ProjectFileType.java
  src/main/java/com/potatoes/cg/project/dto/request/PostUpdateRequest.java
  src/main/java/com/potatoes/cg/project/dto/request/ProjectInviteMemberRequest.java
  src/main/java/com/potatoes/cg/project/dto/request/ProjectPostCreateRequest.java
  src/main/java/com/potatoes/cg/project/dto/request/ProjectUpdateRequest.java
  src/main/java/com/potatoes/cg/project/dto/response/MemberDeptResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/ProjectPostResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/ProjectResponse.java
  src/main/java/com/potatoes/cg/project/presentation/ProjectController.java
  src/main/java/com/potatoes/cg/project/service/PostService.java
  src/main/java/com/potatoes/cg/project/service/ProjectMemberService.java
  src/main/java/com/potatoes/cg/project/service/ProjectService.java
Labels: API, BE

#53 Feat/#39/받은쪽지함검색
  src/main/java/com/potatoes/cg/note/domain/repository/NoteRepository.java
  src/main/java/com/potatoes/cg/note/dto/response/NoteResponse.java
  src/main/java/com/potatoes/cg/note/dto/response/NotesResponse.java
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
Labels: API, BE, Feature

#56 Feat/#40/중요 쪽지함 검색(전체 검색, 카테고리 검색)
  src/main/java/com/potatoes/cg/common/exception/CustomException.java
  src/main/java/com/potatoes/cg/note/domain/repository/NoteRepository.java
  src/main/java/com/potatoes/cg/note/dto/response/NoteResponse.java
  src/main/java/com/potatoes/cg/note/dto/response/NotesResponse.java
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
Labels: API, BE, Feature

#58 Feat/#23/회원관리작업 이메일 임시비밀번호 템플릿 변경
  src/main/java/com/potatoes/cg/member/service/SendEmailService.java
  src/main/resources/static/imgs/sample.png
Labels: API, BE, Feature

#62 Feat/#2/캘린더
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectMemberRepository.java
  src/main/java/com/potatoes/cg/project/service/ProjectMemberService.java
Labels: BE, Feature

#63 Feature/#23/회원관리작업
  src/main/java/com/potatoes/cg/common/config/SecurityConfig.java
  src/main/java/com/potatoes/cg/member/dto/request/MemberPwSendEmailRequest.java
  src/main/java/com/potatoes/cg/member/dto/request/MemberPwdRequest.java
  src/main/java/com/potatoes/cg/member/dto/request/MemberSearchIdRequest.java
  src/main/java/com/potatoes/cg/member/presentation/MemberController.java
  src/main/java/com/potatoes/cg/member/service/MemberService.java
  src/main/java/com/potatoes/cg/member/service/SendEmailService.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectMemberRepository.java
  src/main/java/com/potatoes/cg/project/service/ProjectMemberService.java
  src/main/resources/static/imgs/member/faa85bc159d946e6b0a435bcdc3187b3.jpg
Labels: Bug

#64 Feat/#40/
  src/main/java/com/potatoes/cg/note/domain/repository/NoteRepository.java
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectMemberRepository.java
Labels: API, BE, Feature

#66 Feat / #49 / projectSchedule
  src/main/java/com/potatoes/cg/calendar/domain/Calendar.java
  src/main/java/com/potatoes/cg/calendar/domain/repository/CalendarRepository.java
  src/main/java/com/potatoes/cg/calendar/domain/type/StatusType.java
  src/main/java/com/potatoes/cg/calendar/dto/request/CalendarCreateRequest.java
  src/main/java/com/potatoes/cg/calendar/dto/request/CalendarUpdateRequest.java
  src/main/java/com/potatoes/cg/calendar/dto/response/ScheduleDetailResponse.java
  src/main/java/com/potatoes/cg/calendar/dto/response/ScheduleResponse.java
  src/main/java/com/potatoes/cg/calendar/presentation/CalendarController.java
  src/main/java/com/potatoes/cg/calendar/service/CalendarService.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectMemberRepository.java
  src/main/java/com/potatoes/cg/project/service/PostService.java
  src/main/java/com/potatoes/cg/project/service/ProjectMemberService.java
  src/main/java/com/potatoes/cg/projectSchedule/presentation/ProjectScheduleController.java
  src/main/java/com/potatoes/cg/projectSchedule/service/ProjectScheduleService.java
Labels: BE

#69 Feature/#16/#17/#18/기안서 완성, 결재순서 업데이트
  src/main/java/com/potatoes/cg/approval/domain/Approval.java
  src/main/java/com/potatoes/cg/approval/domain/ApprovalLine.java
  src/main/java/com/potatoes/cg/approval/dto/request/ExpenseCreateRequest.java
  src/main/java/com/potatoes/cg/approval/dto/request/LetterCreateRequest.java
  src/main/java/com/potatoes/cg/approval/dto/request/VacationCreateRequest.java
  src/main/java/com/potatoes/cg/approval/dto/response/AllMemberResponse.java
  src/main/java/com/potatoes/cg/approval/service/ApprovalService.java
Labels: API, BE, Fix

#70 Feat/#23/회원관리작업 회원가입 관련 수정
  src/main/java/com/potatoes/cg/member/domain/MemberInfo.java
  src/main/java/com/potatoes/cg/member/dto/request/MemberSignupRequest.java
  src/main/java/com/potatoes/cg/member/dto/response/SearchInfoResponse.java
  src/main/java/com/potatoes/cg/member/presentation/MemberController.java
  src/main/java/com/potatoes/cg/member/service/MemberService.java
Labels: BE, Feature

#71 Feat/#23/회원관리작업 imgs 폴더 files로 변경
  src/main/java/com/potatoes/cg/common/config/SecurityConfig.java
  src/main/resources/static/imgs/member/3b2de87e1e9d42749f0714066a5181f2.jpg
  src/main/resources/static/imgs/member/549be84937804c0cbd772d0b1a015d6c.jpg
  src/main/resources/static/imgs/member/861e0f1234ee4cab8f34d95620cd0c35.jpg
  src/main/resources/static/imgs/member/e552cc1400584242a9cf2020cab8443b.jpg
  src/main/resources/static/imgs/member/faa85bc159d946e6b0a435bcdc3187b3.jpg
Labels: BE

#72 Feature/#16/#17/#18/완성-수정ver1:approvalService null체크 추가
  src/main/java/com/potatoes/cg/approval/service/ApprovalService.java
Labels: API, BE, Fix

#75 Fix/#47/ 부서별 회원 조회, 검색 수정
  src/main/java/com/potatoes/cg/project/domain/ProjectManager.java
  src/main/java/com/potatoes/cg/project/domain/ProjectTask.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectMemberRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectTaskRepository.java
  src/main/java/com/potatoes/cg/project/dto/response/MemberDeptResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/MyTaskResponse.java
  src/main/java/com/potatoes/cg/project/presentation/ProjectController.java
  src/main/java/com/potatoes/cg/project/service/ProjectMemberService.java
  src/main/java/com/potatoes/cg/project/service/ProjectService.java
  src/main/java/com/potatoes/cg/project/service/TaskService.java
Labels: Bug, BE, Fix

#76 Fix/#75/ 프로젝트 생성 수정
  src/main/java/com/potatoes/cg/project/presentation/ProjectController.java
  src/main/java/com/potatoes/cg/project/service/ProjectService.java
Labels: Bug, Fix

#78 Feature/#23/회원관리작업
  src/main/java/com/potatoes/cg/login/service/LoginService.java
  src/main/java/com/potatoes/cg/member/domain/repository/InfoRepository.java
  src/main/java/com/potatoes/cg/member/domain/repository/MemberRepository.java
  src/main/java/com/potatoes/cg/member/dto/response/NonMembersResponse.java
  src/main/java/com/potatoes/cg/member/presentation/AdminController.java
  src/main/java/com/potatoes/cg/member/service/AdminService.java
  src/main/java/com/potatoes/cg/member/service/MemberService.java
  src/main/java/com/potatoes/cg/project/service/ProjectMemberService.java
  src/main/resources/static/files/member/0496de3e330746d19011aef8261b70ef.png
  src/main/resources/static/files/member/07ea0310b43744fcb098466e57e7609d.png
  src/main/resources/static/files/member/09e6c30fc39a4bb791f8016e64af21e9.png
  src/main/resources/static/files/member/2cc365d03e3245a4812558fab3b50141.png
  src/main/resources/static/files/member/4460fb4550e140da8c7bd60c6f32bbe2.png
  src/main/resources/static/files/member/4cdae740d1364d9d8cd7af08f211a422.png
  src/main/resources/static/files/member/542cf137ed904fef8d0ca4508539783d.png
  src/main/resources/static/files/member/5ad79dfe12c44cc5b5bac9181e4bba62.png
  src/main/resources/static/files/member/5cb1b54e52f0467fa7cff9b47a740e2a.png
  src/main/resources/static/files/member/64e72626e38d42779f3f994e8a72449e.png
  src/main/resources/static/files/member/7a244bebba0349a79dfb82b11f4bfc32.png
  src/main/resources/static/files/member/a0d0ac8596244fc897540ebb0efddc4a.png
  src/main/resources/static/files/member/a68a03f615b44ec9bd75d4c761536131.png
  src/main/resources/static/files/member/b395a0fe825041f09eac48ba49938528.png
  src/main/resources/static/files/member/bc381677b17848239c854466cae071d3.png
  src/main/resources/static/files/member/c8e84a10ca5643578f2bc1c68e23ac84.png
  src/main/resources/static/files/member/f1f79c098d314ba2a1b3228b53bc2838.png
  src/main/resources/static/files/member/fae636474e28457e89d855b803318b51.png
Labels: API, BE, Feature

#79 Feature/#23/회원관리작업
  src/main/java/com/potatoes/cg/login/service/LoginService.java
  src/main/java/com/potatoes/cg/member/domain/MemberInfo.java
  src/main/java/com/potatoes/cg/member/domain/repository/InfoRepository.java
  src/main/java/com/potatoes/cg/member/domain/repository/MemberRepository.java
  src/main/java/com/potatoes/cg/member/domain/type/MemberInfoStatus.java
  src/main/java/com/potatoes/cg/member/dto/response/AdminMembersResponse.java
  src/main/java/com/potatoes/cg/member/dto/response/MemberResponse.java
  src/main/java/com/potatoes/cg/member/dto/response/NonMembersResponse.java
  src/main/java/com/potatoes/cg/member/dto/response/ProfileResponse.java
  src/main/java/com/potatoes/cg/member/presentation/AdminController.java
  src/main/java/com/potatoes/cg/member/presentation/MemberController.java
  src/main/java/com/potatoes/cg/member/service/AdminService.java
  src/main/java/com/potatoes/cg/member/service/MemberService.java
Labels: API, BE, Feature

#80 refactoring/#73/상신함 버그 픽스
  src/main/java/com/potatoes/cg/approval/domain/Approval.java
  src/main/java/com/potatoes/cg/approval/domain/repository/ApprovalRepository.java
  src/main/java/com/potatoes/cg/approval/dto/request/ReportApprovalStatusUpdateRequest.java
  src/main/java/com/potatoes/cg/approval/dto/response/ReportDetail_ExpenseResponse.java
  src/main/java/com/potatoes/cg/approval/dto/response/ReportDetail_LetterResponse.java
  src/main/java/com/potatoes/cg/approval/dto/response/ReportResponse.java
  src/main/java/com/potatoes/cg/approval/presentation/ApprovalController.java
  src/main/java/com/potatoes/cg/approval/service/ApprovalService.java
  src/main/java/com/potatoes/cg/common/util/MultipleFileUploadUtils.java
Labels: Bug, API, Refactor

#84 Feature/#23/회원관리작업
  src/main/java/com/potatoes/cg/member/domain/History.java
  src/main/java/com/potatoes/cg/member/domain/Member.java
  src/main/java/com/potatoes/cg/member/domain/MemberInfo.java
  src/main/java/com/potatoes/cg/member/domain/repository/HistoryRepository.java
  src/main/java/com/potatoes/cg/member/dto/request/MemberPwdRequest.java
  src/main/java/com/potatoes/cg/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/potatoes/cg/member/dto/response/HistoryResponse.java
  src/main/java/com/potatoes/cg/member/dto/response/ProfileResponse.java
  src/main/java/com/potatoes/cg/member/presentation/MemberController.java
  src/main/java/com/potatoes/cg/member/service/MemberService.java
  src/main/resources/static/files/member/bc381677b17848239c854466cae071d3.png
Labels: API, BE, Feature

#85 Feature/#23/회원관리작업
  src/main/resources/static/files/member/bcaea87d18674a82ac4ca8db1ddcfcfe.png
  src/main/resources/static/files/memberBackup/0496de3e330746d19011aef8261b70ef.png
  src/main/resources/static/files/memberBackup/07ea0310b43744fcb098466e57e7609d.png
  src/main/resources/static/files/memberBackup/09e6c30fc39a4bb791f8016e64af21e9.png
  src/main/resources/static/files/memberBackup/2cc365d03e3245a4812558fab3b50141.png
  src/main/resources/static/files/memberBackup/4460fb4550e140da8c7bd60c6f32bbe2.png
  src/main/resources/static/files/memberBackup/4cdae740d1364d9d8cd7af08f211a422.png
  src/main/resources/static/files/memberBackup/542cf137ed904fef8d0ca4508539783d.png
  src/main/resources/static/files/memberBackup/5ad79dfe12c44cc5b5bac9181e4bba62.png
  src/main/resources/static/files/memberBackup/5cb1b54e52f0467fa7cff9b47a740e2a.png
  src/main/resources/static/files/memberBackup/64e72626e38d42779f3f994e8a72449e.png
  src/main/resources/static/files/memberBackup/7a244bebba0349a79dfb82b11f4bfc32.png
  src/main/resources/static/files/memberBackup/a0d0ac8596244fc897540ebb0efddc4a.png
  src/main/resources/static/files/memberBackup/a68a03f615b44ec9bd75d4c761536131.png
  src/main/resources/static/files/memberBackup/b395a0fe825041f09eac48ba49938528.png
  src/main/resources/static/files/memberBackup/bcaea87d18674a82ac4ca8db1ddcfcfe.png
  src/main/resources/static/files/memberBackup/c8e84a10ca5643578f2bc1c68e23ac84.png
  src/main/resources/static/files/memberBackup/f1f79c098d314ba2a1b3228b53bc2838.png
  src/main/resources/static/files/memberBackup/fae636474e28457e89d855b803318b51.png
Labels: Fix

#86 Feat/#1/쪽지쓰기
  src/main/java/com/potatoes/cg/note/domain/Note.java
  src/main/java/com/potatoes/cg/note/domain/repository/NoteRepository.java
  src/main/java/com/potatoes/cg/note/domain/type/NoteStatusType.java
  src/main/java/com/potatoes/cg/note/dto/request/NoteCreateRequest.java
  src/main/java/com/potatoes/cg/note/dto/request/NoteMoveRequest.java
  src/main/java/com/potatoes/cg/note/dto/response/NoteResponse.java
  src/main/java/com/potatoes/cg/note/dto/response/NotesResponse.java
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
  src/main/java/com/potatoes/cg/notice/domain/Notice.java
  src/main/java/com/potatoes/cg/notice/domain/Sample.java
  src/main/java/com/potatoes/cg/notice/domain/type/NoticeOptionType.java
  src/main/java/com/potatoes/cg/notice/domain/type/NoticeStatusType.java
  src/main/java/com/potatoes/cg/notice/domain/type/Sample.java
  src/main/java/com/potatoes/cg/notice/dto/request/NoticeCreateRequest.java
  src/main/java/com/potatoes/cg/notice/dto/response/NoticeResponse.java
  src/main/java/com/potatoes/cg/notice/dto/response/NoticesResponse.java
  src/main/java/com/potatoes/cg/notice/dto/response/Sample.java
  src/main/java/com/potatoes/cg/notice/presentation/NoticeController.java
  src/main/java/com/potatoes/cg/notice/presentation/Sample.java
  src/main/java/com/potatoes/cg/notice/service/NoticeService.java
Labels: API, BE, Feature

#87 Fix/#75/ 오류 수정
  src/main/java/com/potatoes/cg/project/domain/ProjectTask.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectMemberRepository.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectParticipantRepository.java
  src/main/java/com/potatoes/cg/project/dto/response/ProjectPostResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/ProjectTaskResponse.java
  src/main/java/com/potatoes/cg/project/presentation/ProjectController.java
  src/main/java/com/potatoes/cg/project/service/ProjectMemberService.java
  src/main/java/com/potatoes/cg/project/service/TaskService.java
Labels: Bug, BE, Fix

#89 Feat/#4/ 대시보드 할일 조회
  src/main/java/com/potatoes/cg/project/domain/ProjectTask.java
  src/main/java/com/potatoes/cg/project/dto/request/ProjectTaskCreateRequest.java
  src/main/java/com/potatoes/cg/project/dto/request/TaskCheckRequest.java
  src/main/java/com/potatoes/cg/project/dto/request/TaskUpdateRequest.java
  src/main/java/com/potatoes/cg/project/dto/response/MyTodoResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/ProjectsResponse.java
  src/main/java/com/potatoes/cg/project/presentation/ProjectController.java
  src/main/java/com/potatoes/cg/project/service/ProjectService.java
  src/main/java/com/potatoes/cg/project/service/TaskService.java
  src/main/java/com/potatoes/cg/projectTodo/service/ProjectTodoService.java
  src/main/java/com/potatoes/cg/projectTodolist/domain/repository/ProjectTodolistRepository.java
Labels: BE

#90 Feat/#1/쪽지 쓰기
  src/main/java/com/potatoes/cg/note/domain/repository/NoteRepository.java
  src/main/java/com/potatoes/cg/note/dto/response/NoteMemberResponse.java
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
  src/main/java/com/potatoes/cg/note/service/NoteService.java
Labels: API, BE, Feature

#92 Feat/#4/ 대시보드 조회
  src/main/java/com/potatoes/cg/note/dto/response/NotesResponse.java
  src/main/java/com/potatoes/cg/project/domain/repository/ProjectMemberRepository.java
  src/main/java/com/potatoes/cg/project/dto/response/LoginJobInfoResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/MemberDeptResponse.java
  src/main/java/com/potatoes/cg/project/dto/response/MyTaskResponse.java
  src/main/java/com/potatoes/cg/project/presentation/ProjectController.java
  src/main/java/com/potatoes/cg/project/service/ProjectMemberService.java
Labels: BE

#94 Feat / #93 / todo
  src/main/java/com/potatoes/cg/project/domain/ProjectReply.java
  src/main/java/com/potatoes/cg/projectSchedule/domain/repository/ProjectScheduleRepository.java
  src/main/java/com/potatoes/cg/projectSchedule/dto/response/ProjectScheduleResponse.java
  src/main/java/com/potatoes/cg/projectSchedule/service/ProjectScheduleService.java
  src/main/java/com/potatoes/cg/projectTodo/domain/repository/ProjectTodoRepository.java
  src/main/java/com/potatoes/cg/projectTodo/dto/response/ProjectTodoListResponse.java
  src/main/java/com/potatoes/cg/projectTodo/dto/response/ProjectTodoResponse.java
  src/main/java/com/potatoes/cg/projectTodo/service/ProjectTodoService.java
  src/main/java/com/potatoes/cg/projectTodolist/dto/request/ProjectTodolistCreateRequest.java
Labels: BE, Feature

#95 Feature/#23/회원관리작업
  src/main/resources/static/files/member/0a819ac940a646b9aa570c921b5dd386.png
  src/main/resources/static/files/member/a2b508d64f5f4fc7818f4bc4d552654c.png
  src/main/resources/static/files/member/c08e2764216145ebbd7062ab2670e9d7.png
  src/main/resources/static/files/member/efd90e6c7778447296897192d4bf10df.png
Labels: BE

#97 refactorting/코드 수정
  src/main/java/com/potatoes/cg/approval/domain/repository/ApprovalRepository.java
  src/main/java/com/potatoes/cg/approval/domain/type/approvalLineType/ApprovalLineWaitingStatusType.java
  src/main/java/com/potatoes/cg/approval/service/ApprovalService.java
Labels: Refactor

#100 Feat/#11/받은 쪽지함 조회 시 링크 수정
  src/main/java/com/potatoes/cg/note/presentation/NoteController.java
Labels: BE, Feature
